.TH createrepo_mod "1" Manual
.SH NAME
createrepo_mod
.SH SYNOPSIS
.B createrepo_mod
[-h] directory_to_index
.SH DESCRIPTION
A small wrapper around createrepo_c and modifyrepo_c toprovide an easy tool
for generating module repositories
.SH OPTIONS
.TP
\fBdirectory_to_index\fR
Directory to index

.SH AUTHORS
.B createrepo_mod
was written by Jakub Kadlčík <jkadlcik@redhat.com>.
.SH DISTRIBUTION
The latest version of createrepo_mod may be downloaded from
.UR HOMEPAGE
.UE
