.TH modulemd-merge "1" Manual
.SH NAME
modulemd-merge
.SH SYNOPSIS
.B modulemd-merge
[-h] [-v] [-d] [-i] input [input ...] output
.SH DESCRIPTION
Merge several modules.yaml files (rpm modularity metadata) into one.
.SH OPTIONS
.TP
\fBinput\fR
input filename(s) or directories.
repomd.xml files are parsed and modules hrefs contained are merged.
If a directory is given, it is searched for repodata/repomd.xml and repomd.xml

.TP
\fBoutput\fR
YAML output filename

.TP
\fB\-v\fR, \fB\-\-verbose\fR
increase output verbosity

.TP
\fB\-d\fR, \fB\-\-debug\fR
debug output verbosity

.TP
\fB\-i\fR, \fB\-\-ignore\-no\-input\fR
ignore non\-existing input files

.SH AUTHORS
.B modulemd\-merge
was written by Gerd v. Egidy <gerd.von.egidy@intra2net.com>.
.SH DISTRIBUTION
The latest version of modulemd\-merge may be downloaded from
.UR HOMEPAGE
.UE
