.TH "REPO2MODULE" "1" "2020-11-22" "" "repo2module Manual"
.SH NAME
repo2module \- Generates modules.yaml file with a module,...
.SH SYNOPSIS
.B repo2module
[OPTIONS] REPO_PATH [MODULES_YAML]
.SH DESCRIPTION
Generates modules.yaml file with a module, that provides all RPM packages that are available within a repository.
.SH OPTIONS
.TP
\fB\-d,\fP \-\-debug / \-\-nodebug
.PP
.TP
\fB\-n,\fP \-\-module\-name TEXT
[default: (Current directory name)]
.TP
\fB\-s,\fP \-\-module\-stream TEXT
[default: rolling]
.TP
\fB\-v,\fP \-\-module\-version INTEGER
[default: 1]
.TP
\fB\-c,\fP \-\-module\-context TEXT
[default: abcdef12]
