FROM fedora:34

RUN dnf -y update \
    && dnf -y install dnf-plugins-core \
    && dnf -y builddep modulemd-tools \
    && dnf -y install \
    python3-tox

CMD cd /modulemd-tools && ./entrypoint.sh
